version: 1
disable_existing_loggers: no  # 是否覆蓋以前的配置logger
formatters:
        simple:
            format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            datefmt : "%Y-%m-%d %H:%M:%S"

root: #默認情況下配置
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]

loggers: #如果有設定loggers的話會採用，否則採用root設定
    main:
            level: INFO
            handlers: [console, info_file_handler]
            propagate: no
    crawler:
            level: DEBUG
            handlers: [console, info_file_handler]
            propagate: no

handlers:
    console:
            class: logging.StreamHandler
            level: INFO
            formatter: simple
            stream: ext://sys.stdout

    info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: DEBUG
            formatter: simple
            filename: ./nstrend/log/debug.log
            maxBytes: 5242880
            backupCount: 1
            encoding: utf8

    error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: ./nstrend/log/debug.log
            maxBytes: 5242880
            backupCount: 1
            encoding: utf8